### ISSUE TITLE
pydoc-at-point not working with jedi 0.17+

### ISSUE THREAD

**Issue by dakra** [statmobile/pydoc#24]
I have jedi 0.17.2 installed and when I call `pydoc-at-point` I get the following output. (point was at `UUID` function):

```
/tmp/py-KvISWP:2: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
  s = jedi.Script("""from uuid import UUID
/tmp/py-KvISWP:2: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
  s = jedi.Script("""from uuid import UUID
/tmp/py-KvISWP:81: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).infer instead.
  gd = s.goto_definitions()
Traceback (most recent call last):
  File "/tmp/py-KvISWP", line 89, in <module>
    script_modules = list(gd[0]._evaluator.module_cache.iterate_modules_with_names())
AttributeError: 'Name' object has no attribute '_evaluator'
```

**Comment by daanturo** [comment]
This works for me using `python-jedi 0.17.2-1`. 

```elisp
;;;###autoload
(defun pydoc-at-point ()
  "Try to get help for thing at point.
Requires the python package jedi to be installed.

There is no way right now to get to the full module path. This is a known limitation in jedi."
  (interactive)
  (let* ((line (line-number-at-pos))
	 (column (current-column)))

    (pydoc-setup-xref (list #'pydoc (thing-at-point 'word))
		      (called-interactively-p 'interactive))

    (pydoc-with-help-window (pydoc-buffer)
      (call-process-shell-command
       (format "pydoc `python -c \"
import jedi
print(jedi.Script(path= '%s' ).infer(line= %d , column= %d )[0].full_name)
\"`"
	       (buffer-file-name) line column)
       nil standard-output))))
```
Unfortunately, I am unable to reproduce `pydoc-at-point`'s original rich behaviors `(gd[0].full_name, gd[0].module_path, gd[0].line, gd[0].name, gd[0].docstring(), related)`, see [pydoc-at-point](https://github.com/statmobile/pydoc/blob/4459aa1c2cc7648cb1b9c9fcf470d8809a9bc7b3/pydoc.el#L787)' source, otherwise I would have created a pull request (keeping backward compatibility will be a pain, though).

**Comment by chrisg123** [comment]
I get the following error using ```Jedi 0.18.1``` 
```sh
Traceback (most recent call last):
  File "/tmp/py-fmOTZH", line 2, in <module>
    s = jedi.Script("""import sys
TypeError: __init__() takes from 1 to 2 positional arguments but 4 positional arguments (and 1 keyword-only argument) were given
```
Tried downgrading to ```Jedi 0.17.2``` but that gave me the same error @dakra mentioned.

If I have time to look into this further I will come back and update.

**Comment by jkitchin** [comment]
You may try `pydoc-at-point-no-jedi` as a temporary workaround. I haven't tested it much, so if you could take a look at this and see if it works like you want I would appreciate it.

**Comment by dakra** [comment]
Great, your `jedi-0.18` branch works for me.

`pydoc-at-point-no-jedi` never really worked and returned most of the time `No Python documentation found for ...`

**Comment by jkitchin** [comment]
Ok, I have merged that branch in.
