### PR TITLE
Fix #20 using importlib.metadata and importlib_metadata

### LINKED ISSUE #20: Unsupported use of pip.get_installed_modules()
See https://github.com/pypa/pip/issues/5243. `pip.get_installed_modules()` is used in the function `pydoc-user-modules` at `pydoc.el:466`. As detailed in the link, the correct way to access this functionality is to use `pkg_resources` instead of `pip` and then access `pkg_resources.working_set`. If I have time I'll make a pull request soon.

### PR DESCRIPTION
**Pull request by djr7C4**
Since Python 3.8, pydoc-user-modules has been broken due to the pip developers removing pip.get_installed_distributions. This pull request fixes this by using importlib.metadata (new in Python 3.8) or importlib_metadata (a backport of importlib.metadata) when importlib.metadata is not available (Python 2.x and older versions of Python 3). This means that the code will also work with Python 2 and Python 3.4-3.7 so long as the importlib_metadata package is installed.

### CODE REVIEW

**Comment by djr7C4** [comment]
Ping.

**Comment by jkitchin** [comment]
This does not seem to work for me.

If I run this:

```
(shell-command-to-string
     ;; Use either importlib_metadata (a backport of importlib.metadata) or
     ;; importlib.metadata itself if it is available.
     (concat python-shell-interpreter " -c \"try: import importlib_metadata;implib_meta = importlib_metadata\nexcept: pass\ntry: import importlib.metadata;implib_meta = importlib.metadata\nexcept: implib_meta = None\nmods = sorted(map(lambda x: x.metadata['name'], implib_meta.distributions())); print('({})'.format(' '.join(['\"{}\"'.format(x) for x in mods])))  \""))
```
I get this:

#+RESULTS:
: Traceback (most recent call last):
:   File "<string>", line 5, in <module>
: AttributeError: 'NoneType' object has no attribute 'distributions'

I am not sure it does what you expect, the second try seems to overwrite the first try, and in my case (on python 3.7) results in implib_meta=None. It seems ok without the second try statement.

**Comment by djr7C4** [comment]
I am not sure why, but I can't reproduce the issue you are having with it.  

The idea with overwriting it is to prefer importlib.metadata over importlib_metadata (the backport version).  I tested it prior to submitting the PR with Python 3.8.0 and 2.7.17 and it worked correctly for both of those.

After installing Python 3.7.6, it still works correctly for me as long importlib_meta is installed.  I am not sure why it is broken for you but I will push a more robust version shortly so hopefully that will help.

**Comment by jkitchin** [comment]
The new version seems to work fine for me. I will go ahead and merge this. Thanks for the help!

**Comment by djr7C4** [comment]
No problem!  Thanks for this package!
